#!/bin/bash

# Development variables:
#   export GIT_DIR=$(pwd)/.snap.git
#   export GIT_WORK_TREE=$(pwd)

function abspath() {
  cd -P -- "$(dirname -- "$1")" &&
  echo "$(pwd -P)/$(basename -- "$1")"
}

export GIT_DIR=$HOME/.snap.git
export GIT_WORK_TREE=$HOME

if [[ ! -d $GIT_DIR ]] ; then
  git init
fi

file="$1"

if [[ -z $file ]] ; then
  echo "Please specify a file."
  exit 1
fi

file=$(abspath "$file")

git add "$file"
git commit -m "$file"
