#!/bin/bash

# Development variables:
#   export GIT_DIR=$(pwd)/.snap.git
#   export GIT_WORK_TREE=$(pwd)

file="$1"

export GIT_DIR=$HOME/.snap.git

if [[ ! -d $GIT_DIR ]] ; then
  git init
fi

git add "$file"
git commit -m "$file"
